-- 00_setup.sql
-- One-time environment setup: roles, warehouses, database, schemas, and grants.
-- Run as SECURITYADMIN and SYSADMIN per Snowflake best practices.

-- ----------
-- RBAC
-- ----------
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS DE_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS DE_INGEST_ROLE;
CREATE ROLE IF NOT EXISTS DE_TRANSFORM_ROLE;
CREATE ROLE IF NOT EXISTS DE_ANALYTICS_ROLE;

-- Role hierarchy
GRANT ROLE DE_INGEST_ROLE TO ROLE DE_ADMIN_ROLE;
GRANT ROLE DE_TRANSFORM_ROLE TO ROLE DE_ADMIN_ROLE;
GRANT ROLE DE_ANALYTICS_ROLE TO ROLE DE_ADMIN_ROLE;

-- Analyst role: can query gold (PII masked, region filtered)
CREATE ROLE IF NOT EXISTS DE_ANALYST_ROLE;
GRANT ROLE DE_ANALYST_ROLE TO ROLE DE_ADMIN_ROLE;

-- Assign DE_ADMIN_ROLE to your user (replace <your_user>)
-- GRANT ROLE DE_ADMIN_ROLE TO USER <your_user>;

-- ----------
-- Warehouses (cost-aware sizing)
-- ----------
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS INGEST_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Ingestion workloads (COPY INTO, light transforms)';

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
  WITH WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Silver/gold transformations and DQ checks';

CREATE WAREHOUSE IF NOT EXISTS ANALYTICS_WH
  WITH WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Ad hoc analytics and BI';

-- ----------
-- Database and Schemas
-- ----------
CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB
  DATA_RETENTION_TIME_IN_DAYS = 7
  COMMENT = 'E-commerce pipeline database (bronze/silver/gold)';

CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.UTIL;

-- ----------
-- Grants
-- ----------
GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE DE_INGEST_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DE_TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE DE_ANALYTICS_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE DE_ANALYST_ROLE;

GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE DE_INGEST_ROLE;
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE DE_TRANSFORM_ROLE;
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE DE_ANALYTICS_ROLE;
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE DE_ANALYST_ROLE;

GRANT USAGE ON SCHEMA ECOMMERCE_DB.BRONZE TO ROLE DE_INGEST_ROLE;
GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK
  ON SCHEMA ECOMMERCE_DB.BRONZE TO ROLE DE_INGEST_ROLE;

GRANT USAGE ON SCHEMA ECOMMERCE_DB.SILVER TO ROLE DE_TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STREAM, CREATE TASK
  ON SCHEMA ECOMMERCE_DB.SILVER TO ROLE DE_TRANSFORM_ROLE;

GRANT USAGE ON SCHEMA ECOMMERCE_DB.GOLD TO ROLE DE_TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE
  ON SCHEMA ECOMMERCE_DB.GOLD TO ROLE DE_TRANSFORM_ROLE;

GRANT USAGE ON SCHEMA ECOMMERCE_DB.GOLD TO ROLE DE_ANALYTICS_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_DB.GOLD TO ROLE DE_ANALYTICS_ROLE;
ALTER SCHEMA ECOMMERCE_DB.GOLD SET MANAGED ACCESS = TRUE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.GOLD TO ROLE DE_ANALYTICS_ROLE;

GRANT USAGE ON SCHEMA ECOMMERCE_DB.GOLD TO ROLE DE_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_DB.GOLD TO ROLE DE_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.GOLD TO ROLE DE_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ECOMMERCE_DB.GOLD TO ROLE DE_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ECOMMERCE_DB.GOLD TO ROLE DE_ANALYST_ROLE;

GRANT USAGE ON SCHEMA ECOMMERCE_DB.UTIL TO ROLE DE_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA ECOMMERCE_DB.UTIL TO ROLE DE_INGEST_ROLE;
GRANT CREATE TABLE, CREATE PROCEDURE
  ON SCHEMA ECOMMERCE_DB.UTIL TO ROLE DE_TRANSFORM_ROLE;
GRANT CREATE PROCEDURE
  ON SCHEMA ECOMMERCE_DB.UTIL TO ROLE DE_INGEST_ROLE;

-- ----------
-- GDPR compliance grants (allow transform role to delete from bronze for GDPR)
-- ----------
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_DB.BRONZE TO ROLE DE_TRANSFORM_ROLE;
GRANT DELETE ON ALL TABLES IN SCHEMA ECOMMERCE_DB.BRONZE TO ROLE DE_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.BRONZE TO ROLE DE_TRANSFORM_ROLE;
GRANT DELETE ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.BRONZE TO ROLE DE_TRANSFORM_ROLE;

-- Suppression list access (checked during ingestion + silver merge)
-- These grants are applied after GDPR_SUPPRESSION_LIST is created by 51_gdpr_compliance.sql.
-- Run these after initial setup or include in a post-setup script:
-- GRANT SELECT, INSERT ON TABLE ECOMMERCE_DB.UTIL.GDPR_SUPPRESSION_LIST TO ROLE DE_TRANSFORM_ROLE;
-- GRANT SELECT ON TABLE ECOMMERCE_DB.UTIL.GDPR_SUPPRESSION_LIST TO ROLE DE_INGEST_ROLE;

-- End of setup
