-- 22_silver_streams.sql
-- Silver-to-Gold streams: capture incremental changes for the gold build.
-- These streams are consumed by SP_BUILD_GOLD_BATCH and SP_BUILD_GOLD_EVENTS.

USE ROLE DE_TRANSFORM_ROLE;
USE WAREHOUSE TRANSFORM_WH;
USE DATABASE ECOMMERCE_DB;
USE SCHEMA SILVER;

-- Dimension sources (track inserts + updates)
CREATE OR REPLACE STREAM CUSTOMERS_STREAM
  ON TABLE CUSTOMERS
  APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM PRODUCTS_STREAM
  ON TABLE PRODUCTS
  APPEND_ONLY = FALSE;

-- Fact sources (track inserts + updates)
CREATE OR REPLACE STREAM ORDERS_STREAM
  ON TABLE ORDERS
  APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM PAYMENTS_STREAM
  ON TABLE PAYMENTS
  APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM RETURNS_STREAM
  ON TABLE RETURNS
  APPEND_ONLY = FALSE;

-- Events (append-only, immutable facts)
CREATE OR REPLACE STREAM EVENTS_STREAM
  ON TABLE EVENTS
  APPEND_ONLY = TRUE;
