-- 11_streams.sql
-- Streams capture incremental changes from bronze to silver.

USE ROLE DE_INGEST_ROLE;
USE WAREHOUSE INGEST_WH;
USE DATABASE ECOMMERCE_DB;
USE SCHEMA BRONZE;

CREATE OR REPLACE STREAM CUSTOMERS_RAW_STREAM
  ON TABLE CUSTOMERS_RAW
  APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM PRODUCTS_RAW_STREAM
  ON TABLE PRODUCTS_RAW
  APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM ORDERS_RAW_STREAM
  ON TABLE ORDERS_RAW
  APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM PAYMENTS_RAW_STREAM
  ON TABLE PAYMENTS_RAW
  APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM RETURNS_RAW_STREAM
  ON TABLE RETURNS_RAW
  APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM EVENTS_RAW_STREAM
  ON TABLE EVENTS_RAW
  APPEND_ONLY = TRUE;
