-- tasks.sql
-- Orchestration with Snowflake Tasks (dependencies + retries).

USE ROLE DE_ADMIN_ROLE;
USE DATABASE ECOMMERCE_DB;
USE SCHEMA UTIL;

-- Root task: batch ingestion (hourly)
CREATE OR REPLACE TASK TASK_INGEST_BATCH
  WAREHOUSE = INGEST_WH
  SCHEDULE = 'USING CRON 0 * * * * America/Los_Angeles'
  USER_TASK_TIMEOUT_MS = 900000
AS
  CALL UTIL.SP_INGEST_BATCH();

-- Root task: event ingestion (every 5 minutes)
CREATE OR REPLACE TASK TASK_INGEST_EVENTS
  WAREHOUSE = INGEST_WH
  SCHEDULE = 'USING CRON */5 * * * * America/Los_Angeles'
  USER_TASK_TIMEOUT_MS = 300000
AS
  CALL UTIL.SP_INGEST_EVENTS();

-- Merge into silver after ingestion completes
CREATE OR REPLACE TASK TASK_MERGE_SILVER
  WAREHOUSE = TRANSFORM_WH
  AFTER TASK_INGEST_BATCH, TASK_INGEST_EVENTS
  USER_TASK_TIMEOUT_MS = 900000
AS
  CALL UTIL.SP_MERGE_SILVER();

-- Build gold after silver
CREATE OR REPLACE TASK TASK_BUILD_GOLD
  WAREHOUSE = TRANSFORM_WH
  AFTER TASK_MERGE_SILVER
  USER_TASK_TIMEOUT_MS = 900000
AS
  CALL UTIL.SP_BUILD_GOLD();

-- Data quality checks after gold
CREATE OR REPLACE TASK TASK_DQ_CHECKS
  WAREHOUSE = TRANSFORM_WH
  AFTER TASK_BUILD_GOLD
  USER_TASK_TIMEOUT_MS = 300000
AS
  CALL UTIL.SP_RUN_DQ_CHECKS();

-- Sessionization + reconciliation views are built inside SP_BUILD_GOLD,
-- so no separate task is needed. Views refresh on read.

-- Retry behavior (suspend after repeated failures)
ALTER TASK TASK_INGEST_BATCH SET SUSPEND_TASK_AFTER_NUM_FAILURES = 3;
ALTER TASK TASK_INGEST_EVENTS SET SUSPEND_TASK_AFTER_NUM_FAILURES = 5;
ALTER TASK TASK_MERGE_SILVER SET SUSPEND_TASK_AFTER_NUM_FAILURES = 3;
ALTER TASK TASK_BUILD_GOLD SET SUSPEND_TASK_AFTER_NUM_FAILURES = 3;
ALTER TASK TASK_DQ_CHECKS SET SUSPEND_TASK_AFTER_NUM_FAILURES = 3;

-- Resume tasks (order matters: children first)
ALTER TASK TASK_DQ_CHECKS RESUME;
ALTER TASK TASK_BUILD_GOLD RESUME;
ALTER TASK TASK_MERGE_SILVER RESUME;
ALTER TASK TASK_INGEST_EVENTS RESUME;
ALTER TASK TASK_INGEST_BATCH RESUME;
